(async()=>{'use strict';
const route=await fetch('./descent-route.json').then(r=>{if(!r.ok)throw Error('route');return r.json()});
const plates=[document.getElementById('plate-a'),document.getElementById('plate-b')],view=document.getElementById('view'),seed=document.getElementById('seed'),phase=document.getElementById('phase'),prev=document.getElementById('prev'),next=document.getElementById('next');let index=0,slot=0,busy=false,serial=0;
const back=document.getElementById('leaves-back'),front=document.getElementById('leaves-front'),portal=document.getElementById('portal'),dialog=document.getElementById('portal-dialog');
portal.onclick=()=>{if(!busy)dialog.showModal()};document.getElementById('portal-close').onclick=()=>{dialog.close();portal.focus()};
const cache=new Map();function ready(src){if(!cache.has(src)){const im=new Image();im.src=src;cache.set(src,im.decode());}return cache.get(src);}
async function show(n){if(busy||n<0||n>=route.frames.length)return;busy=true;portal.hidden=true;prev.disabled=next.disabled=true;phase.textContent='Aproximando…';const frame=route.frames[n],token=++serial;try{await Promise.all([ready(frame.asset),ready('./assets/frondosa-leaves.webp')]);if(token!==serial)return;slot=1-slot;const target=plates[slot];target.src=frame.asset;target.style.transform='scale('+frame.zoomStart+') rotate('+frame.roll+'deg)';target.classList.add('active');plates[1-slot].classList.remove('active');index=n;const inCanopy=n>=1&&n<=3;back.style.opacity=inCanopy?'.8':'0';front.style.opacity=inCanopy?'1':'0';back.style.transform='translate('+[-8,0,5,-5,0][n]+'%, '+[-10,5,15,-20,0][n]+'%) scale(.85) rotate(180deg)';front.style.transform='translate('+[0,-10,-22,12,0][n]+'%, '+[0,-10,10,-28,0][n]+'%) scale(1.1) rotate('+[0,5,-5,10,0][n]+'deg)';seed.style.left=frame.seedX+'%';seed.style.top=frame.seedY+'%';seed.style.rotate=frame.windRoll+'deg';document.getElementById('art').textContent=frame.id;document.getElementById('title').textContent=frame.title;document.getElementById('counter').textContent=(n+1)+' / '+route.frames.length;requestAnimationFrame(()=>requestAnimationFrame(()=>target.style.transform='scale('+frame.zoomEnd+') rotate('+frame.roll+'deg)'));const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;setTimeout(()=>{if(token!==serial)return;busy=false;portal.hidden=n!==2;prev.disabled=n===0;next.disabled=n===route.frames.length-1;phase.textContent=n===route.frames.length-1?'WAIT · Trilha para Patita · continuação em construção':'WAIT · Observe · deslize ↑ ou avance';},reduced?0:1750);if(route.frames[n+1])ready(route.frames[n+1].asset).catch(()=>{});}catch(e){busy=false;phase.textContent='Não foi possível carregar a arte. Tente avançar novamente.';prev.disabled=index===0;next.disabled=false;}}
prev.onclick=()=>show(index-1);next.onclick=()=>show(index+1);let start=null;view.addEventListener('pointerdown',e=>{if(e.target.closest('button,a'))return;view.setPointerCapture(e.pointerId);start={x:e.clientX,y:e.clientY}});view.addEventListener('pointerup',e=>{if(!start)return;const dy=start.y-e.clientY,dx=start.x-e.clientX;start=null;if(Math.abs(dy)>55&&Math.abs(dy)>Math.abs(dx))show(index+(dy>0?1:-1));});view.addEventListener('pointercancel',()=>start=null);document.addEventListener('keydown',e=>{if(e.target.closest('button,a,input,select,textarea'))return;if(['ArrowDown','ArrowRight',' '].includes(e.key)){e.preventDefault();show(index+1)}if(['ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();show(index-1)}});const tools=document.getElementById('tools'),settings=document.getElementById('settings');tools.onclick=()=>{settings.hidden=!settings.hidden;tools.setAttribute('aria-expanded',String(!settings.hidden))};document.addEventListener('keydown',e=>{if(e.key==='Escape'){settings.hidden=true;tools.setAttribute('aria-expanded','false');tools.focus()}});show(0);
})().catch(()=>document.getElementById('phase').textContent='Falha ao carregar o roteiro. Recarregue a página.');
